power <- read.table("household_power_consumption/household_power_consumption.txt", sep = ";", h=T)
datetime <- paste(power$Date, power$Time)
datetime <- as.POSIXct(strptime(datetime, "%d/%m/%Y %H:%M:%S"))
power <- cbind(datetime, power[,-(1:2)])
power <- subset(power, datetime >= as.POSIXct("2007-02-01 00:00:00 PST") & datetime <= as.POSIXct("2007-02-02 23:59:59 PST"))
power$Sub_metering_1 = as.numeric(as.character(power$Sub_metering_1))
power$Sub_metering_2 = as.numeric(as.character(power$Sub_metering_2))
power$Sub_metering_3 = as.numeric(as.character(power$Sub_metering_3))

png("plot3.png", width = 480, height = 480)
plot(power$Sub_metering_1 ~ power$datetime, type = "l", main = "", ylab = "Energy sub metering", xlab = "")
lines(power$Sub_metering_2 ~ power$datetime, col = "Red")
lines(power$Sub_metering_3 ~ power$datetime, col = "Blue")
legend("topright", col = c("Black", "Red", "Blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1)
dev.off()